apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressvalidationverone
spec:
  selector:
    matchLabels:
      app: addressvalidationverone
  replicas: 3
  template:
    metadata:
      labels:
        app: addressvalidationverone
    spec:
      containers:
      - name: addressvalidationcontainer
        image: abhayshitole/devops-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: addressvalidationverone
spec:
  selector:
    app: addressvalidationverone
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort